SELECT table_name FROM information_schema.tables WHERE table_type = 'base table';


select count(*) from admin_user union all
select count(*) from administrative_district union all
select count(*) from app_version union all
select count(*) from billiard_club union all
select count(*) from billiard_club_album union all
select count(*) from billiard_club_album_map union all
select count(*) from billiard_club_benefit union all
select count(*) from billiard_club_comment union all
select count(*) from billiard_club_facility union all
select count(*) from billiard_club_facility_map union all
select count(*) from billiard_club_log union all
select count(*) from billiard_club_membership_subscription_ticket union all
select count(*) from billiard_club_offer_benefit union all
select count(*) from billiard_club_offer_benefit_map union all
select count(*) from billiard_club_table_charge union all
select count(*) from billiard_club_table_charge_map union all
select count(*) from billiard_table union all
select count(*) from billiard_table_map union all
select count(*) from coach union all
select count(*) from coach_private_memo union all
select count(*) from coach_private_memo_map union all
select count(*) from company union all
select count(*) from company_own_billiard_club union all
select count(*) from company_own_billiard_club_user union all
select count(*) from competition union all
select count(*) from competition_comment union all
select count(*) from competition_place union all
select count(*) from competition_player union all
select count(*) from competition_record union all
select count(*) from competition_rule union all
select count(*) from competition_table union all
select count(*) from competition_table_game_matching_map union all
select count(*) from cue union all
select count(*) from cue_brand union all
select count(*) from cue_brand_log union all
select count(*) from cue_model union all
select count(*) from cue_model_log union all
select count(*) from cue_review union all
select count(*) from cue_trade_marketplace union all
select count(*) from currency union all
select count(*) from dashboard union all
select count(*) from dashboard_content union all
select count(*) from dashboard_content_log union all
select count(*) from dashboard_content_view_count_history union all
select count(*) from dashboard_log union all
select count(*) from dutch_auction union all
select count(*) from dutch_auction_alarm union all
select count(*) from dutch_auction_push_log union all
select count(*) from event union all
select count(*) from event_log union all
select count(*) from event_view_count_history union all
select count(*) from favorite_billiard_club union all
select count(*) from forum union all
select count(*) from forum_post union all
select count(*) from forum_post_comment union all
select count(*) from forum_post_like union all
select count(*) from game union all
select count(*) from game_matching union all
select count(*) from game_matching_record_log union all
select count(*) from game_matching_request union all
select count(*) from game_matching_request_log union all
select count(*) from game_matching_user_attendance union all
select count(*) from game_matching_user_attendance_map union all
select count(*) from game_record union all
select count(*) from game_record_map union all
select count(*) from lesson union all
select count(*) from lesson_information union all
select count(*) from lesson_message union all
select count(*) from lesson_review union all
select count(*) from pardus_cafe_crawl_data union all
select count(*) from payment union all
select count(*) from play_note union all
select count(*) from play_note_page union all
select count(*) from play_note_page_table union all
select count(*) from play_note_page_video union all
select count(*) from post union all
select count(*) from post_block union all
select count(*) from post_block_album_item union all
select count(*) from post_block_ball_item union all
select count(*) from post_block_table_item union all
select count(*) from post_block_text_item union all
select count(*) from post_image union all
select count(*) from product union all
select count(*) from product_album union all
select count(*) from product_model union all
select count(*) from product_model_group union all
select count(*) from product_order union all
select count(*) from product_order_item union all
select count(*) from product_order_shipping union all
select count(*) from promotion_exposed_area union all
select count(*) from promotion_exposed_area_map union all
select count(*) from qmiss union all
select count(*) from qmiss_admin_user union all
select count(*) from qmiss_comment union all
select count(*) from qmiss_commnet union all
select count(*) from qmiss_member union all
select count(*) from qmiss_notice union all
select count(*) from qmiss_promotion union all
select count(*) from scoring_company union all
select count(*) from scoring_company_billiard_club union all
select count(*) from student union all
select count(*) from sys_event_log union all
select count(*) from system_notification union all
select count(*) from tv_channel union all
select count(*) from tv_channel_movie union all
select count(*) from tv_promotion union all
select count(*) from user union all
select count(*) from user_access_log union all
select count(*) from user_album union all
select count(*) from user_album_map union all
select count(*) from user_attendance union all
select count(*) from user_attendance_map union all
select count(*) from user_external_certification union all
select count(*) from user_game_matching union all
select count(*) from user_lesson_information union all
select count(*) from user_lesson_information_contents union all
select count(*) from user_like_billiard_club union all
select count(*) from user_list_open_status_log union all
select count(*) from user_notification union all
select count(*) from user_preferred_area union all
select count(*) from user_profile union all
select count(*) from user_push_notification union all
select count(*) from user_push_notification_topic union all
select count(*) from user_schedule union all
select count(*) from user_social union all
select count(*) from user_social_map ;
